language:
  - objective-c

matrix:
  include:
    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx

    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx10.9

    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      xcode_scheme: UnzipKitDemo
      xcode_sdk: iphonesimulator

before_script:
  - ./Scripts/install-demo-libs.sh

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Release analyze test

after_script:
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false